services:
  bot:
    image: ghcr.io/fyko/scer-legendary-bot:latest
    env_file:
      - stack.env
    restart: unless-stopped
    volumes:
      - /data/scer/sqlite:/app/data/
      
  mysql:
    image: mysql:9.3.0
    volumes:
      - mysql-storage:/var/lib/mysql
    env_file:
      - stack.env
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-storage:
